version: '3.8'


services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: swc_client
    ports:
      - ${CLIENT_PORT:-4000}:${CLIENT_PORT:-4000}
    command: [
      "yarn",
      "start"
    ]
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CLIENT_PORT=${CLIENT_PORT:-4000}
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public