FROM node:20.11.0-alpine as build
WORKDIR /home/node/app
COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY . .


#Build
RUN yarn run build 


FROM nginx:latest as server
COPY --from=build /home/node/app/build/ /usr/share/nginx/html/
CMD ["nginx", "-g", "daemon off;"]